Base/urls.py
from django.urls import path, include
from Base import views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name="Inicio"),
    path('noticias/', views.noticias, name="Noticias"),
    path('tienda/', views.tienda, name="Tienda"),
    path('about/', views.nosotros, name="Nosotros"),
    path('contacto/', views.contacto, name="Contacto"),
    path('', RedirectView.as_view(url='/Base/', permanent=True)), # Para que ingrese directamente a nuestra pagina
]

#Clase 24 --> Para las imagenes
urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog/urls.py
from django.urls import path
from Blog import views


urlpatterns = [
    path('', views.blog, name="Pages"),
    path('publicar/', views.posteo, name='Posteo'),
    path('pages/', views.leerPosteos, name = "LeerPosteos"),
    path('post/<title>',views.post, name="Publicacion"),
    path(r'^editar/(?P<pk>\d+)$', views.PostUpdate.as_view(), name='Edit'),
    path(r'^borrar/(?P<pk>\d+)$', views.PostDelete.as_view(), name='Delete'),
    
]

ProyectoFinal/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Base.urls')),
    path('accounts/', include('Signup.urls')),
    path('Inicio/', include('Blog.urls')),
    path('accounts/', include('Login.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    titulo = models.CharField(max_length=100)
    subtitulo = models.CharField(max_length=200)
    parrafo = models.CharField(max_length=2000)
    autor = models.CharField(max_length=50)
    fecha = models.DateField(auto_now_add=True, auto_now=False)
    imagen = models.ImageField(null = True, blank=True, upload_to='imagenes/')

    def __str__(self):
        return f"Titulo: {self.titulo} --- Subtitulo: {self.subtitulo} --- Parrafo: {self.parrafo} --- Autor: {self.autor} --- Fecha: {self.fecha} --- Imagen: {self.imagen}"

'''
class Categoria(models.Model):
    id = models.AutoField(primary_key= True)
    nombre = models.CharField('Nombre de la Categoria', max_length=100, null=False,blank=False)
    estado = models.BooleanField('Categoria activada / Categoria Desactivada', default=True)
    fecha_creacion=models.DateField('Fecha de creacion', auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name='Categoría'
        verbose_name_plural='Categorías'
    
    def __str__(self):
        return self.nombre

class Autor(models.Model):
    id = models.AutoField(primary_key=True)
    nombres=models.CharField('Nombres de autor', max_length=255, null=False, blank=False)
    apellidos=models.CharField('Apellidos de autor', max_length=255, null=False,blank=False)
    facebook=models.URLField('Facebook', null = True, blank=True)
    twitter=models.URLField('Twitter', null = True, blank=True)
    instagram=models.URLField('Instagram', null = True, blank=True)
    youtube=models.URLField('Youtube', null = True, blank=True)
    web=models.URLField('Web', null=True,blank=True)
    correo=models.EmailField('Correo Electronico', blank=False, null=False)
    estado=models.BooleanField('Autor Activo/Inactivo', default=True)
    fecha_creacion=models.DateField('Fecha de creacion', auto_now=False, auto_now_add=True)
    
    class Meta:
        verbose_name='Autor'
        verbose_name_plural='Autores'

    def __str__(self):
        return "{0},{1}".format(self.apellidos, self.nombres)

'''

Blog/forms.py
from pyexpat import model
from django import forms
from .models import Post

'''
class SignupForm(forms.Form):
    usuario=forms.CharField(max_length=30, widget=forms.TextInput(attrs={"class":"form-control p-4", 'placeholder': 'Ingrese usuario'}),required=True)
    correo=forms.EmailField(max_length=50, widget=forms.TextInput(attrs={"class":"form-control p-4", 'placeholder': 'Ingrese correo electrónico'}),required=True)
    contraseña=forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={"class":"form-control p-4", 'placeholder': 'Ingrese contraseña'}),required=True)
'''
class PostForm(forms.Form):
    titulo = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class":"form-control p-4", 'placeholder': 'Titulo'}),required=True)
    subtitulo = forms.CharField(max_length=200, widget=forms.TextInput(attrs={"class":"form-control p-4", 'placeholder': 'Subtitulo'}),required=True)
    parrafo = forms.CharField(max_length=2000, widget=forms.Textarea(attrs={"class":"form-control p-4", 'placeholder': 'Contenido'}),required=True)
    autor = forms.CharField(max_length=50, widget=forms.TextInput(attrs={"class":"form-control p-4", 'placeholder': 'Autor'}),required=True)
    #fecha = forms.DateField(widget=forms.DateInput(attrs={"class":"form-control p-4"}))
    imagen = forms.ImageField()

Blog/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from Blog.forms import PostForm
from Blog.models import Post

# Create your views here.

@login_required
def blog(request):
      return render(request, "Blog/blog.html")

@login_required
def posteo(request):
      if request.POST:
            posteo = Post()
            posteo.titulo = request.POST.get('titulo')
            posteo.subtitulo = request.POST.get('subtitulo')
            posteo.parrafo = request.POST.get('parrafo')
            posteo.autor = request.POST.get('autor')
            posteo.imagen = request.FILES.get('imagen')

            posteo.save()

            return render(request, "Base/pages/index.html")
      
      return render(request, "Blog/publicar.html")

@login_required
def leerPosteos(request):

      posteos = Post.objects.all() #trae todos los profesores

      contexto= {"posteos":posteos} 

      return render(request, "Blog/blog.html",contexto)

@login_required
def post(request, title):
      id_post = Post.objects.get(id=title)
      '''
      subtitulo = request.POST.get('subtitulo')
      parrafo = request.POST.get('parrafo')
      autor = request.POST.get('autor')
      imagen = request.FILES.get('imagen')
      '''
      return render(request, "Blog/post.html",{'detalle':id_post})

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


class PostUpdate(UpdateView):

    model = Post
    success_url = "/Inicio/pages"
    fields = ['titulo', 'subtitulo', 'parrafo', 'autor', 'imagen']

class PostDelete(DeleteView):

    model = Post
    success_url = "/Inicio/pages"

'''
      if request.method == 'POST':

            miFormulario = PostForm(request.POST) #aquí mellega toda la información del html

            print(miFormulario)

            if miFormulario.is_valid:   #Si pasó la validación de Django

            
                  informacion = miFormulario.cleaned_data

                  post = Post(titulo=informacion['titulo'], subtitulo=informacion['subtitulo'],
                   parrafo=informacion['parrafo'], autor=informacion['autor']) 

                  post.save()

                  return render(request, "Base/pages/index.html") #Vuelvo al inicio o a donde quieran

      else: 

            miFormulario= PostForm() #Formulario vacio para construir el html

      return render(request, "Blog/publicar.html", {"miFormulario":miFormulario})
      '''

Blog/templates/Blog/blog.html
{% extends "Base/template.html" %}
{% load static %}
{% block contenidoQueCambia %}
<!-- Posteos -->
<main class="container-fluid mt-5 pt-3">
    <section class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h4 class="m-0 text-uppercase font-weight-bold">Últimas Publicaciones</h4>
                            <a href="{% url 'Posteo' %}">Publicar</a>
                        </div>
                    </div>
                    {% for p in posteos%}

                    <div class="col-lg-12">
                        <div class="row news-lg mx-0 mb-3">
                            <div class="col-md-6 h-100 px-0">
                                <img class="img-fluid h-100" src="{{p.imagen.url}}" style="object-fit: cover;">
                            </div>
                            <div class="col-md-6 d-flex flex-column border bg-white h-100 px-0">
                                <div class="mt-auto px-4 py-3">
                                    <div class="mb-2">
                                        <a class="badge badge-primary text-uppercase font-weight-semi-bold p-2 mr-2"
                                            href="">Business</a>
                                        <a class="text-body" href=""><small>{{p.fecha}}</small></a>
                                    </div>
                                    <h3 class="h4 d-block mb-3 text-secondary text-uppercase font-weight-bold">{{p.titulo}}</h3>
                                    <p class="mb-3">{{p.subtitulo}}</p> 
                                    <a href="{% url 'Publicacion' p.id %}" class="btn btn-primary font-weight-semi-bold px-4" style="padding: 5px 10px;"
                                        type="submit">Leer Más
                                    </a>
                                    <div class="text-right">
                                        | <a href="{% url 'Edit' p.id %}">Editar</a> | <a href="{% url 'Delete' p.id %}">Borrar</a> |
                                    </div>
                                </div>
                                <div class="d-flex justify-content-between bg-white border-top mt-auto p-4">
                                    <div class="d-flex align-items-center">
                                        <img class="rounded-circle mr-2" src="{% static 'Base/img/user.jpg' %}" width="25" height="25" alt="">
                                        <small>{{p.autor}}</small>
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <small class="ml-3"><i class="far fa-eye mr-2"></i>12345</small>
                                        <small class="ml-3"><i class="far fa-comment mr-2"></i>123</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            
            <div class="col-lg-4">
                <!-- Social Follow Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Follow Us</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-3">
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #39569E;">
                            <i class="fab fa-facebook-f text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Fans</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #52AAF4;">
                            <i class="fab fa-twitter text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Followers</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #0185AE;">
                            <i class="fab fa-linkedin-in text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Connects</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #C8359D;">
                            <i class="fab fa-instagram text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Followers</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #DC472E;">
                            <i class="fab fa-youtube text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Subscribers</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none" style="background: #055570;">
                            <i class="fab fa-vimeo-v text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Followers</span>
                        </a>
                    </div>
                </div>
                <!-- Social Follow End -->

                <!-- Ads Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Advertisement</h4>
                    </div>
                    <div class="bg-white text-center border border-top-0 p-3">
                        <a href=""><img class="img-fluid" src="{% static 'Base/img/news-800x500-2.jpg' %}" alt=""></a>
                    </div>
                </div>
                <!-- Ads End -->

                <!-- Popular News Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Tranding News</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-3">
                        <div class="d-flex align-items-center bg-white mb-3" style="height: 110px;">
                            <img class="img-fluid" src="{% static 'Base/img/news-110x110-1.jpg' %}" alt="">
                            <div class="w-100 h-100 px-3 d-flex flex-column justify-content-center border border-left-0">
                                <div class="mb-2">
                                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="">Business</a>
                                    <a class="text-body" href=""><small>Jan 01, 2045</small></a>
                                </div>
                                <a class="h6 m-0 text-secondary text-uppercase font-weight-bold" href="">Lorem ipsum dolor sit amet elit...</a>
                            </div>
                        </div>
                        <div class="d-flex align-items-center bg-white mb-3" style="height: 110px;">
                            <img class="img-fluid" src="{% static 'Base/img/news-110x110-2.jpg' %}" alt="">
                            <div class="w-100 h-100 px-3 d-flex flex-column justify-content-center border border-left-0">
                                <div class="mb-2">
                                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="">Business</a>
                                    <a class="text-body" href=""><small>Jan 01, 2045</small></a>
                                </div>
                                <a class="h6 m-0 text-secondary text-uppercase font-weight-bold" href="">Lorem ipsum dolor sit amet elit...</a>
                            </div>
                        </div>
                        <div class="d-flex align-items-center bg-white mb-3" style="height: 110px;">
                            <img class="img-fluid" src="{% static 'Base/img/news-110x110-3.jpg' %}" alt="">
                            <div class="w-100 h-100 px-3 d-flex flex-column justify-content-center border border-left-0">
                                <div class="mb-2">
                                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="">Business</a>
                                    <a class="text-body" href=""><small>Jan 01, 2045</small></a>
                                </div>
                                <a class="h6 m-0 text-secondary text-uppercase font-weight-bold" href="">Lorem ipsum dolor sit amet elit...</a>
                            </div>
                        </div>
                        <div class="d-flex align-items-center bg-white mb-3" style="height: 110px;">
                            <img class="img-fluid" src="{% static 'Base/img/news-110x110-4.jpg' %}" alt="">
                            <div class="w-100 h-100 px-3 d-flex flex-column justify-content-center border border-left-0">
                                <div class="mb-2">
                                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="">Business</a>
                                    <a class="text-body" href=""><small>Jan 01, 2045</small></a>
                                </div>
                                <a class="h6 m-0 text-secondary text-uppercase font-weight-bold" href="">Lorem ipsum dolor sit amet elit...</a>
                            </div>
                        </div>
                        <div class="d-flex align-items-center bg-white mb-3" style="height: 110px;">
                            <img class="img-fluid" src="{% static 'Base/img/news-110x110-5.jpg' %}" alt="">
                            <div class="w-100 h-100 px-3 d-flex flex-column justify-content-center border border-left-0">
                                <div class="mb-2">
                                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="">Business</a>
                                    <a class="text-body" href=""><small>Jan 01, 2045</small></a>
                                </div>
                                <a class="h6 m-0 text-secondary text-uppercase font-weight-bold" href="">Lorem ipsum dolor sit amet elit...</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Popular News End -->

                <!-- Newsletter Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Newsletter</h4>
                    </div>
                    <div class="bg-white text-center border border-top-0 p-3">
                        <p>Aliqu justo et labore at eirmod justo sea erat diam dolor diam vero kasd</p>
                        <div class="input-group mb-2" style="width: 100%;">
                            <input type="text" class="form-control form-control-lg" placeholder="Your Email">
                            <div class="input-group-append">
                                <button class="btn btn-primary font-weight-bold px-3">Sign Up</button>
                            </div>
                        </div>
                        <small>Lorem ipsum dolor sit amet elit</small>
                    </div>
                </div>
                <!-- Newsletter End -->

                <!-- Tags Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Tags</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-3">
                        <div class="d-flex flex-wrap m-n1">
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Politics</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Business</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Corporate</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Business</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Health</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Education</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Science</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Business</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Foods</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Travel</a>
                        </div>
                    </div>
                </div>
                <!-- Tags End -->
            </div>
        </div>
    </section>
</main>
<!-- End Posteos -->
{% endblock %}

Blog/templates/Blog/post_confirm_delete.html
{% extends "Base/template.html" %}

{% load static %}
{% block contenidoQueCambia %}
<!-- Publicar Start -->
<style>
    #id_titulo, #id_subtitulo, #id_parrafo, #id_autor {
        display: block;
        width: 100%;
        height: calc(1.5em + 0.75rem + 2px);
        padding: 1.5rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: 0;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }
</style>
<main class="container-fluid">
    <section class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="row">
            <div>
                <div class="section-title mb-0">
                    <h4 class="m-0 text-uppercase font-weight-bold">Borrar</h4>
                </div>
                <div class="bg-white border border-top-0 p-4 mb-3">
                    <h6 class="text-uppercase font-weight-bold mb-3">Eliminar post</h6>
                    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
                        <div class="form-group">
                            <p>¿Estas seguro que deseas eleiminar "{{object.titulo}}"?</p>
                        </div>
                        <div>
                            <button class="btn btn-primary font-weight-semi-bold px-4" style="height: 50px;"
                                type="submit">Borrar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</main>
<!-- Publicar End -->
{% endblock %}

Blog/templates/Blog/post_form.html
{% extends "Base/template.html" %}

{% load static %}
{% block contenidoQueCambia %}
<!-- Publicar Start -->
<style>
    #id_titulo, #id_subtitulo, #id_parrafo, #id_autor {
        display: block;
        width: 100%;
        height: calc(1.5em + 0.75rem + 2px);
        padding: 1.5rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: 0;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }
</style>
<main class="container-fluid">
    <section class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="row">
            <div>
                <div class="section-title mb-0">
                    <h4 class="m-0 text-uppercase font-weight-bold">Editar</h4>
                </div>
                <div class="bg-white border border-top-0 p-4 mb-3">
                    <h6 class="text-uppercase font-weight-bold mb-3">Editar posteo</h6>
                    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
                        
                        <div class="form-group">
                            {{ form.titulo }}
                        </div>
                        <div class="form-group">
                            {{ form.subtitulo }}
                        </div>
                        <div class="form-group">
                            {{ form.parrafo }}
                        </div>
                        <div class="form-group">
                            {{ form.autor }}
                        </div>
                        <div class="form-group">
                            {{ form.imagen }}
                        </div>
                        <!--
                        <div class="form-group">
                            <input type="date" name="fecha">
                        </div>
                        -->
                        <div>
                            <button class="btn btn-primary font-weight-semi-bold px-4" style="height: 50px;"
                                type="submit">Editar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</main>
<!-- Publicar End -->
{% endblock %}

Blog/templates/Blog/publicar.html
{% extends "Base/template.html" %}

{% load static %}
{% block contenidoQueCambia %}
<!-- Publicar Start -->
<main class="container-fluid">
    <section class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="row">
            <div>
                <div class="section-title mb-0">
                    <h4 class="m-0 text-uppercase font-weight-bold">Publicar</h4>
                </div>
                <div class="bg-white border border-top-0 p-4 mb-3">
                    <h6 class="text-uppercase font-weight-bold mb-3">Nuevo posteo</h6>
                    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control p-4" name="titulo" placeholder="Titulo">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control p-4" name="subtitulo" placeholder="Subtitulo">
                        </div>
                        <div class="form-group">
                            <textarea type="text" class="form-control p-4" name="parrafo" placeholder="Post"></textarea>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control p-4" name="autor" placeholder="Autor">
                        </div>
                        <div class="form-group">
                            <input type="file" name="imagen">
                        </div>
                        <!--
                        <div class="form-group">
                            <input type="date" name="fecha">
                        </div>
                        -->
                        <div>
                            <button class="btn btn-primary font-weight-semi-bold px-4" style="height: 50px;"
                                type="submit">Publicar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</main>
<!-- Publicar End -->
{% endblock %}